packages:
  centos:
    common:
      packages:
      - bind-utils
      - curl
      - dnsmasq
      - edk2-ovmf
      - firewalld
      - httpd-tools
      - jq
      - libguestfs-tools
      - libguestfs-tools
      - libvirt
      - libvirt-daemon-kvm
      - libvirt-devel
      - NetworkManager
      - nmap
      - patch
      - podman
      - polkit-pkla-compat
      - psmisc
      - python3-libvirt
      - python3-lxml
      - python3-netaddr
      - python3-requests-oauthlib
      - python3-six
      - qemu-img
      - qemu-kvm
      - unzip
      - vim-enhanced
      - virt-install
      - wget
    el9:
      packages:
      - genisoimage
      - python3-bcrypt
    el10:
      packages:
      - xorriso
    pip3:
    - flask_oauthlib==0.9.6
    - jmespath
    - kubernetes==25.3.0
    - passlib
DAEMON_JSON_PATH: ""
CONTAINER_RUNTIME: "{{ lookup('env', 'CONTAINER_RUNTIME') }}"
OS_VERSION_ID: "{{ lookup('env', 'OS_VERSION_ID') }}"
REGISTRY: "{{ lookup('env', 'REGISTRY') }}"
DOCKER_IPV6_SUPPORT: "{{ lookup('env', 'DOCKER_USE_IPV6_INTERNALLY') | default('false', true) }}"
ANSIBLE_VENV: "{{ lookup('env', 'ANSIBLE_VENV') | default('/usr', true) }}"
# Go related variables, expected to be updated when new versions are released:
go_version: "1.25.14"
# Construct Go download URL and tarball name
go_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
go_tarball: "go{{ go_version }}.linux-{{ go_arch }}.tar.gz"
go_download_url: "https://go.dev/dl/{{ go_tarball }}"
