#!/usr/bin/env bash
set -euxo pipefail

source logging.sh
source common.sh
source network.sh
source utils.sh
source ocp_install_env.sh
source rhcos.sh
source validation.sh

early_deploy_validation

set_api_and_ingress_vip

if [ ! -f "${OCP_DIR}/install-config.yaml" ]; then
    NODES_LEN=$(jq '.nodes | length' "${NODES_FILE}")
    if (( NODES_LEN < NUM_MASTERS + NUM_WORKERS )); then
        echo "ERROR: ${NODES_FILE} contains ${NODES_LEN} nodes, but ${NUM_MASTERS} masters and ${NUM_WORKERS} workers requested"
        exit 1
    fi

    # Generate base config vars from the resolved bash environment
    SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    "${SCRIPTDIR}/ansible/vars_bridge.sh"

    EXTRA_VARS_FILE="${SCRIPTDIR}/ansible/.runtime_vars.yml"

    # Append runtime-computed values that vars_bridge.sh does not cover
    cat > "${EXTRA_VARS_FILE}" << RUNTIME_EOF
# Runtime vars generated by 05_create_install_config.sh
devscripts_machine_os_bootstrap_image_name: "${MACHINE_OS_BOOTSTRAP_IMAGE_NAME}"
devscripts_machine_os_bootstrap_image_sha256: "${MACHINE_OS_BOOTSTRAP_IMAGE_UNCOMPRESSED_SHA256}"
devscripts_nodes_file: "${NODES_FILE}"
devscripts_ocp_dir: "${OCP_DIR}"
devscripts_scriptdir: "${SCRIPTDIR}"
RUNTIME_EOF

    # BMC verify CA certificate (OCP >= 4.22)
    BMC_CA_FILE="${WORKING_DIR}/virtualbmc/sushy-tools/cert.pem"
    if [[ -f "${BMC_CA_FILE}" ]] && ! is_lower_version "$(openshift_version "${OCP_DIR}")" "4.22"; then
        {
            echo 'devscripts_bmc_verify_ca: |'
            sed 's/^/  /' "${BMC_CA_FILE}"
        } >> "${EXTRA_VARS_FILE}"
    fi

    # Image mirror content sources and trust bundle
    MIRROR_CONTENT=$(image_mirror_config || true)
    if [[ -n "${MIRROR_CONTENT}" ]]; then
        # Extract imageContentSources as JSON array for the template
        ICS_YAML=$(echo "${MIRROR_CONTENT}" | sed -n '/^imageContentSources:/,/^[a-zA-Z]/p' | sed '$d')
        if [[ -n "${ICS_YAML}" ]]; then
            echo "${ICS_YAML}" >> "${EXTRA_VARS_FILE}"
        fi

        # Extract additionalTrustBundle content
        TRUST_BUNDLE=$(echo "${MIRROR_CONTENT}" | sed -n '/^additionalTrustBundle:/,$ p')
        if [[ -n "${TRUST_BUNDLE}" ]]; then
            {
                echo "devscripts_additional_trust_bundle_content: |"
                echo "${TRUST_BUNDLE}" | tail -n +2
            } >> "${EXTRA_VARS_FILE}"
        fi
    elif [[ -n "${ADDITIONAL_TRUST_BUNDLE:-}" ]]; then
        {
            echo "devscripts_additional_trust_bundle_content: |"
            awk '{ print "  ", $0 }' "${ADDITIONAL_TRUST_BUNDLE}"
        } >> "${EXTRA_VARS_FILE}"
    fi

    # Proxy variables (when INSTALLER_PROXY is set)
    if [[ -n "${INSTALLER_PROXY:-}" ]]; then
        cat >> "${EXTRA_VARS_FILE}" << PROXY_EOF
devscripts_http_proxy: "${HTTP_PROXY}"
devscripts_https_proxy: "${HTTPS_PROXY}"
devscripts_no_proxy: "${NO_PROXY}"
PROXY_EOF
    fi

    ANSIBLE_FORCE_COLOR=true ansible-playbook \
        -i "${SCRIPTDIR}/ansible/inventory/hosts" \
        --extra-vars "@${SCRIPTDIR}/ansible/.config_vars.yml" \
        --extra-vars "@${EXTRA_VARS_FILE}" \
        -v \
        "${SCRIPTDIR}/ansible/playbooks/install_config.yml"
fi

# Generate the assets for extra worker VMs (not yet migrated to Ansible)
if [ -f "${EXTRA_NODES_FILE}" ]; then
    jq '.nodes' "${EXTRA_NODES_FILE}" | tee "${EXTRA_BAREMETALHOSTS_FILE}"
    generate_ocp_host_manifest "${OCP_DIR}" "${EXTRA_BAREMETALHOSTS_FILE}" extra_host_manifests.yaml "${EXTRA_WORKERS_NAMESPACE}"
fi

if [ -f "${ARM_NODES_FILE}" ]; then
    jq '.nodes' "${ARM_NODES_FILE}" | tee "${EXTRA_ARM_BAREMETALHOSTS_FILE}"
    generate_ocp_host_manifest "${OCP_DIR}" "${EXTRA_ARM_BAREMETALHOSTS_FILE}" extra_arm_host_manifests.yaml "${EXTRA_WORKERS_NAMESPACE}"
fi
