#!/bin/bash

IFACE=$1
STATUS=$2

case "$STATUS" in
    pre-up)
    logger -s "NM dns-vip-prepender triggered by pre-upping ${1}."
    CLUSTER_DOMAIN="$(/usr/local/bin/clusterinfo DOMAIN)"
    if ! HOST_QUERY="$(host ns1.${CLUSTER_DOMAIN})" ; then
        logger -s "NM dns-vip-prepender: nameserver could not be resolved, exiting"
        exit 0
    fi
    DNS_VIP=$(echo "${HOST_QUERY}" | awk '{print $NF}')
    if [[ -n $DNS_VIP ]]; then
        logger -s "NM dns-vip-prepender: Checking if DNS VIP is the first entry in resolv.conf"
        if grep nameserver /etc/resolv.conf | head -n 1 | grep -q "$DNS_VIP" ; then
            logger -s "NM dns-vip-prepender: DNS VIP already the first entry in resolv.conf"
            exit 0
        else
            export DNS_VIP

            logger -s "NM dns-vip-prepender: Setting dhclient to prepend DNS VIP in resolv.conf"
            envsubst < /etc/dhcp/dhclient.conf.template | tee /etc/dhcp/dhclient.conf

            logger -s "NM dns-vip-prepender: Looking for 'search $CLUSTER_DOMAIN' in /etc/resolv.conf to place 'nameserver $DNS_VIP'"
            sed -i "/^search .*$/a nameserver $DNS_VIP" /etc/resolv.conf
        fi
    fi
    ;;
    down)
    logger -s "NM dns-vip-prepender triggered by downing $IFACE"
    ;;
    up)
    logger -s "NM dns-vip-prepender triggered by upping $IFACE"
    ;;
    post-down)
    logger -s "NM dns-vip-prepender triggered by post-downing $IFACE"
    ;;
    *)
    ;;
esac
