# This Dockerfile builds the image used by the e2e-metal-ipi test steps in the OpenShift CI.
# For more details about the test see https://steps.svc.ci.openshift.org/job/openshift-baremetal-operator-master-e2e-metal-ipi

FROM centos:7
RUN yum -y install python3 git && \
    yum clean all && \
    pip3 install ansible packet-python 
RUN mkdir /root/src
WORKDIR /root/src

