---

- set_fact:
    generate_vm_nodes: "{{vm_nodes is not defined}}"

- name: "Show network_mode data for debugging (common role)"
  debug:
    var: networks_nat_only

- name: Set an empty default for vm_nodes if not already defined
  set_fact:
    vm_nodes: []
  when: generate_vm_nodes

- name: Populate vm_nodes if not already defined
  when: generate_vm_nodes
  include_tasks: vm_nodes_tasks.yml
  loop: "{{flavors|dict2items}}"
  loop_control:
    loop_var: flavor

- debug:
    var: vm_nodes
  when: generate_vm_nodes

- name: "Check if EXTRA_NETWORK_NAMES is configured"
  set_fact:
    generate_extra_networks: "{{lookup('env', 'EXTRA_NETWORK_NAMES') and extra_networks is not defined}}"

- name: Calculate extra_networks if EXTRA_NETWORK_NAMES is defined
  include_tasks: extra_networks_tasks.yml
  loop: "{{lookup('env', 'EXTRA_NETWORK_NAMES')|split()}}"
  loop_control:
    loop_var: network_name
  when: generate_extra_networks

- name: "Append extra networks when EXTRA_NETWORK_NAMES is configured"
  set_fact:
    networks: "{{ networks + extra_networks }}"
  when: generate_extra_networks

- name: "Show networks data for debugging (common role)"
  debug:
    var: networks
