#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

# shellcheck source=agent/manifests.sh
source "${repo_root}/agent/manifests.sh"

test_root="$(mktemp -d)"
trap 'rm -rf "${test_root}"' EXIT

source_dir="${test_root}/source"
destination="${test_root}/destination"
mkdir -p "${source_dir}" "${destination}"
export SCRIPTDIR="${repo_root}"
export EXTRA_MANIFESTS_PATH="${destination}"

assert_file_content() {
	local expected="$1"
	local path="$2"

	if [[ ! -f "${path}" ]] || [[ "$(<"${path}")" != "${expected}" ]]; then
		echo "expected ${path} to contain: ${expected}" >&2
		return 1
	fi
}

assert_fails() {
	local description="$1"
	shift

	if "$@"; then
		echo "expected failure: ${description}" >&2
		return 1
	fi
	printf 'verified expected failure: %s\n' "${description}"
}

assert_generated_manifests() {
	assert_file_content $'apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: agent-test\n  namespace: openshift-config\ndata:\n  value: agent-test' \
		"${destination}/agent-test.yaml"
	for generated_mce_manifest in "${repo_root}"/agent/mce/agent_mce_0_*.yaml; do
		cmp "${generated_mce_manifest}" "${destination}/${generated_mce_manifest##*/}"
	done
}

# An unset or empty source must retain manifests generated by the agent flow.
export AGENT_DEPLOY_MCE=true
unset ASSETS_EXTRA_FOLDER
generate_extra_cluster_manifests
assert_generated_manifests
export ASSETS_EXTRA_FOLDER=
generate_extra_cluster_manifests
assert_generated_manifests

# An empty source directory is also a no-op.
export ASSETS_EXTRA_FOLDER="${source_dir}"
generate_extra_cluster_manifests
assert_generated_manifests

# Caller-supplied files are copied verbatim, including YAML/YML manifests and
# names containing spaces.
cat >"${source_dir}/custom-mcp.yaml" <<'EOF'
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: custom
spec:
  paused: true
EOF
printf '%s\n' 'apiVersion: v1' 'kind: ConfigMap' >"${source_dir}/other supplied.yml"
printf '%s\n' 'supplied collision' >"${source_dir}/collision.yaml"

generate_extra_cluster_manifests

cmp "${source_dir}/custom-mcp.yaml" "${destination}/custom-mcp.yaml"
cmp "${source_dir}/other supplied.yml" "${destination}/other supplied.yml"
assert_file_content 'supplied collision' "${destination}/collision.yaml"
assert_generated_manifests

# Supplied files are copied last and intentionally override generated agent and
# MCE manifests with the same basename. Non-colliding generated MCE files remain.
mce_override_source="${repo_root}/agent/mce/agent_mce_0_01_lso_namespace.yaml"
mce_override_name="${mce_override_source##*/}"
printf '%s\n' 'supplied agent-test override' >"${source_dir}/agent-test.yaml"
printf '%s\n' 'supplied MCE override' >"${source_dir}/${mce_override_name}"

generate_extra_cluster_manifests

assert_file_content 'supplied agent-test override' "${destination}/agent-test.yaml"
assert_file_content 'supplied MCE override' "${destination}/${mce_override_name}"
for generated_mce_manifest in "${repo_root}"/agent/mce/agent_mce_0_*.yaml; do
	if [[ "${generated_mce_manifest##*/}" != "${mce_override_name}" ]]; then
		cmp "${generated_mce_manifest}" "${destination}/${generated_mce_manifest##*/}"
	fi
done
echo "verified supplied manifests and generated-file overrides"

# A configured source which does not exist must fail visibly.
export ASSETS_EXTRA_FOLDER="${test_root}/missing"
assert_fails 'missing source directory' generate_extra_cluster_manifests

# A direct child which cp cannot copy without recursion makes the copy fail,
# instead of being silently ignored.
copy_failure_source="${test_root}/copy-failure"
mkdir -p "${copy_failure_source}/directory"
export ASSETS_EXTRA_FOLDER="${copy_failure_source}"
assert_fails 'copy operation' generate_extra_cluster_manifests

# The function remains in the configure phase, which precedes image creation.
grep -q '^source .*agent/manifests.sh' "${repo_root}/agent/05_agent_configure.sh"
grep -q '^  generate_extra_cluster_manifests$' "${repo_root}/agent/05_agent_configure.sh"
grep -Eq '^agent: .*agent_configure agent_create_cluster' "${repo_root}/Makefile"

echo "extra manifest copy tests passed"
