#!/usr/bin/env bash
#
# Bridges the existing config.sh into Ansible extra-vars YAML.
#
# Sources common.sh and network.sh to resolve all defaults (including
# IP-stack-dependent values), then writes a YAML file that can be
# passed to ansible-playbook via --extra-vars @file.
#
# Usage:
#   ./ansible/vars_bridge.sh [output_file]
#
# Default output: ansible/.config_vars.yml
#
set -euo pipefail

[[ "${DEBUG:-}" == "true" ]] && set -x

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Source the full dev-scripts config chain
# shellcheck source=/dev/null
source "${SCRIPTDIR}/common.sh"
# shellcheck source=/dev/null
source "${SCRIPTDIR}/network.sh"

OUTPUT="${1:-${SCRIPTDIR}/ansible/.config_vars.yml}"

quote_yaml() {
    local val="${1:-}"
    if [[ -z "${val}" ]]; then
        echo '""'
    elif [[ "${val}" =~ ^(true|false|[0-9]+)$ ]]; then
        echo "${val}"
    else
        echo "\"${val//\"/\\\"}\""
    fi
}

cat > "${OUTPUT}" << ENDOFVARS
# Auto-generated by vars_bridge.sh — do not edit manually.
# Re-generate with: ./ansible/vars_bridge.sh
#
# This file is passed to ansible-playbook as --extra-vars @file
# and overrides group_vars defaults with the user's config.sh values.

# Cluster identity
devscripts_cluster_name: $(quote_yaml "${CLUSTER_NAME}")
devscripts_base_domain: $(quote_yaml "${BASE_DOMAIN}")
devscripts_working_dir: $(quote_yaml "${WORKING_DIR}")
devscripts_ssh_pub_key: $(quote_yaml "${SSH_PUB_KEY}")

# Release
devscripts_release_stream: $(quote_yaml "${OPENSHIFT_RELEASE_STREAM}")
devscripts_release_type: $(quote_yaml "${OPENSHIFT_RELEASE_TYPE}")
devscripts_release_image: $(quote_yaml "${OPENSHIFT_RELEASE_IMAGE}")
devscripts_openshift_version: $(quote_yaml "${OPENSHIFT_VERSION}")
devscripts_openshift_ci: ${OPENSHIFT_CI:-false}

# Features
devscripts_fips_mode: ${FIPS_MODE:-false}
devscripts_feature_set: $(quote_yaml "${FEATURE_SET:-}")
devscripts_feature_gates: $(quote_yaml "${FEATURE_GATES:-}")
devscripts_os_image_stream: $(quote_yaml "${OS_IMAGE_STREAM:-}")

# Capabilities
devscripts_baseline_capability_set: $(quote_yaml "${BASELINE_CAPABILITY_SET:-}")
devscripts_additional_capabilities: $(quote_yaml "${ADDITIONAL_CAPABILITIES:-}")

# Workload partitioning
devscripts_enable_workload_partitioning: $([[ -n "${ENABLE_WORKLOAD_PARTITIONING:-}" ]] && echo "true" || echo "false")

# Node counts
devscripts_num_masters: ${NUM_MASTERS}
devscripts_num_workers: ${NUM_WORKERS}
devscripts_num_arbiters: ${NUM_ARBITERS}
devscripts_num_extra_workers: ${NUM_EXTRA_WORKERS}

# BMC
devscripts_bmc_driver: $(quote_yaml "${BMC_DRIVER}")

# Misc
devscripts_disable_multicast: ${DISABLE_MULTICAST}
devscripts_enable_bootstrap_static_ip: $([[ -n "${ENABLE_BOOTSTRAP_STATIC_IP}" ]] && echo "true" || echo "false")
devscripts_external_loadbalancer: $([[ -n "${EXTERNAL_LOADBALANCER}" ]] && echo "true" || echo "false")

# Network
devscripts_ip_stack: $(quote_yaml "${IP_STACK}")
devscripts_host_ip_stack: $(quote_yaml "${HOST_IP_STACK}")
devscripts_provisioning_network_profile: $(quote_yaml "${PROVISIONING_NETWORK_PROFILE}")
devscripts_provisioning_network_name: $(quote_yaml "${PROVISIONING_NETWORK_NAME}")
devscripts_baremetal_network_name: $(quote_yaml "${BAREMETAL_NETWORK_NAME}")
devscripts_provisioning_network: $(quote_yaml "${PROVISIONING_NETWORK}")
devscripts_external_subnet_v4: $(quote_yaml "${EXTERNAL_SUBNET_V4}")
devscripts_external_subnet_v6: $(quote_yaml "${EXTERNAL_SUBNET_V6}")
devscripts_cluster_subnet_v4: $(quote_yaml "${CLUSTER_SUBNET_V4}")
devscripts_cluster_subnet_v6: $(quote_yaml "${CLUSTER_SUBNET_V6}")
devscripts_cluster_host_prefix_v4: $(quote_yaml "${CLUSTER_HOST_PREFIX_V4}")
devscripts_cluster_host_prefix_v6: $(quote_yaml "${CLUSTER_HOST_PREFIX_V6}")
devscripts_service_subnet_v4: $(quote_yaml "${SERVICE_SUBNET_V4}")
devscripts_service_subnet_v6: $(quote_yaml "${SERVICE_SUBNET_V6}")
devscripts_network_type: $(quote_yaml "${NETWORK_TYPE}")
devscripts_cluster_provisioning_interface: $(quote_yaml "${CLUSTER_PRO_IF}")
devscripts_installer_proxy: $([[ -n "${INSTALLER_PROXY}" ]] && echo "true" || echo "false")
devscripts_installer_proxy_port: ${INSTALLER_PROXY_PORT}

# Registry / mirror
devscripts_enable_local_registry: $([[ -n "${ENABLE_LOCAL_REGISTRY}" ]] && echo "true" || echo "false")
devscripts_registry_backend: $(quote_yaml "${REGISTRY_BACKEND}")
devscripts_registry_port: $(quote_yaml "${LOCAL_REGISTRY_PORT}")
devscripts_registry_user: $(quote_yaml "${REGISTRY_USER}")
devscripts_registry_pass: $(quote_yaml "${REGISTRY_PASS}")
devscripts_registry_dir: $(quote_yaml "${REGISTRY_DIR}")
devscripts_registry_dns_name: $(quote_yaml "${LOCAL_REGISTRY_DNS_NAME}")
devscripts_registry_crt: $(quote_yaml "${REGISTRY_CRT}")
devscripts_mirror_images: $([[ -n "${MIRROR_IMAGES}" && "${MIRROR_IMAGES,,}" != "false" ]] && echo "true" || echo "false")
devscripts_mirror_command: $(quote_yaml "${MIRROR_COMMAND}")
devscripts_mirror_olm: $(quote_yaml "${MIRROR_OLM:-}")
devscripts_mirror_custom_images: $(quote_yaml "${MIRROR_CUSTOM_IMAGES:-}")
devscripts_additional_trust_bundle: $(quote_yaml "${ADDITIONAL_TRUST_BUNDLE:-}")
ENDOFVARS

echo "Config bridge: wrote ${OUTPUT}" >&2
