#!/bin/bash

IFACE=$1
STATUS=$2

case "$STATUS" in
    up)
    logger -s "NM dns-vip-prepender triggered by upping ${1}."
    set -e
    CLUSTER_DOMAIN="$(awk '/search/ {print $2}' /etc/resolv.conf)"
    DNS_VIP="$(dig +noall +answer "ns1.${CLUSTER_DOMAIN}" | awk '{print $NF}')"
    set +e
    if [[ -n $DNS_VIP ]]; then
        logger -s "NM dns-vip-prepender: Checking if DNS VIP is the first entry in resolv.conf"
        if grep nameserver /etc/resolv.conf | head -n 1 | grep -q "$DNS_VIP" ; then
            logger -s "NM dns-vip-prepender: DNS VIP already the first entry in resolv.conf"
            exit 0
        else
            export DNS_VIP

            logger -s "NM dns-vip-prepender: Setting dhclient to prepend DNS VIP in resolv.conf"
            envsubst < /etc/dhcp/dhclient.conf.template | tee /etc/dhcp/dhclient.conf

            logger -s "NM dns-vip-prepender: Looking for 'search $CLUSTER_DOMAIN' in /etc/resolv.conf to place 'nameserver $DNS_VIP'"
            sed -i "/^search ${CLUSTER_DOMAIN}$/a nameserver $DNS_VIP" /etc/resolv.conf
        fi
    fi
    ;;
    down)
    logger -s "NM dns-vip-prepender triggered by downing $IFACE"
    ;;
    pre-up)
    logger -s "NM dns-vip-prepender triggered by pre upping $IFACE"
    ;;
    post-down)
    logger -s "NM dns-vip-prepender triggered by post-downing $IFACE"
    ;;
    *)
    ;;
esac
