#!/bin/bash

IFACE=$1
STATUS=$2

case "$STATUS" in
    up)
    logger -s "NM dns-vip-prepender triggered by upping ${1}."
    set -e
    CLUSTER_DOMAIN="$(awk '/search/ {print $2}' /etc/resolv.conf)"
    API_VIP="$(dig +noall +answer "api.${CLUSTER_DOMAIN}" | awk '{print $NF}')"
    IFACE_CIDRS="$(ip addr show | grep -v "scope host" | grep -Po 'inet \K[\d.]+/[\d.]+' | xargs)"
    SUBNET_CIDR="$(/usr/local/bin/get_vip_subnet_cidr "$API_VIP" "$IFACE_CIDRS")"
    DNS_VIP="$(/usr/local/bin/nthhost "$SUBNET_CIDR" 2)"
    set +e
    if [[ -n $DNS_VIP ]]; then
        logger -s "NM dns-vip-prepender: Checking if DNS VIP is the first entry in resolv.conf"
        if grep nameserver /etc/resolv.conf | head -n 1 | grep -q "$DNS_VIP" ; then
            logger -s "NM dns-vip-prepender: DNS VIP already the first entry in resolv.conf"
            exit 0
        else
            export DNS_VIP

            logger -s "NM dns-vip-prepender: Setting dhclient to prepend DNS VIP in resolv.conf"
            envsubst < /etc/dhcp/dhclient.conf.template | tee /etc/dhcp/dhclient.conf

            logger -s "NM dns-vip-prepender: resetting the connection $CONNECTION_UUID"
            nmcli c down "$CONNECTION_UUID" && nmcli c up "$CONNECTION_UUID"
        fi
    fi
    ;;
    down)
    logger -s "NM dns-vip-prepender triggered by downing $IFACE"
    ;;
    pre-up)
    logger -s "NM dns-vip-prepender triggered by pre upping $IFACE"
    ;;
    post-down)
    logger -s "NM dns-vip-prepender triggered by post-downing $IFACE"
    ;;
    *)
    ;;
esac
