# This manifest is configuring enp2s0 and enp3s0 to form a br-ex bond.
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 00-nmstate-brex-bond-worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,aW50ZXJmYWNlczoKLSBuYW1lOiBib25kMAogIHR5cGU6IGJvbmQKICBzdGF0ZTogdXAKICBpcHY0OgogICAgZW5hYmxlZDogZmFsc2UKICBsaW5rLWFnZ3JlZ2F0aW9uOgogICAgbW9kZTogYWN0aXZlLWJhY2t1cAogICAgb3B0aW9uczoKICAgICAgbWlpbW9uOiAnMTAwJwogICAgcG9ydDoKICAgIC0gZW5wMnMwCiAgICAtIGVucDNzMAotIG5hbWU6IGJyLWV4CiAgdHlwZTogb3ZzLWJyaWRnZQogIHN0YXRlOiB1cAogIGlwdjQ6CiAgICBlbmFibGVkOiBmYWxzZQogICAgZGhjcDogZmFsc2UKICBpcHY2OgogICAgZW5hYmxlZDogZmFsc2UKICAgIGRoY3A6IGZhbHNlCiAgYnJpZGdlOgogICAgcG9ydDoKICAgIC0gbmFtZTogYm9uZDAKICAgIC0gbmFtZTogYnItZXgKLSBuYW1lOiBici1leAogIHR5cGU6IG92cy1pbnRlcmZhY2UKICBzdGF0ZTogdXAKICBpcHY0OgogICAgZW5hYmxlZDogdHJ1ZQogICAgZGhjcDogdHJ1ZQogIGlwdjY6CiAgICBlbmFibGVkOiBmYWxzZQogICAgZGhjcDogZmFsc2U=
          mode: 0644
          overwrite: true
          path: /etc/nmstate/openshift/cluster.yml